"""Initial migration

Revision ID: 7274f3a17147
Revises: 
Create Date: 2024-10-23 17:03:22.796173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7274f3a17147'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mac_addresses',
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('mac_address')
    )
    op.create_table('s3_files',
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('filename')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aws_access_key_id', sa.String(), nullable=True),
    sa.Column('aws_secret_access_key', sa.String(), nullable=True),
    sa.Column('bucket_name', sa.String(), nullable=True),
    sa.Column('dt_rule', sa.Text(), nullable=False),
    sa.Column('max_file_size', sa.Integer(), nullable=False),
    sa.Column('use_cloud', sa.Boolean(), nullable=False),
    sa.Column('delete_scans', sa.Boolean(), nullable=False),
    sa.Column('delete_scans_days_old', sa.Integer(), nullable=True),
    sa.Column('delete_scans_percent_remaining', sa.Integer(), nullable=True),
    sa.Column('device_name_includes', sa.String(), nullable=True),
    sa.Column('id_file_starts_with', sa.String(), nullable=True),
    sa.Column('alert_email', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('s3_files')
    op.drop_table('mac_addresses')
    # ### end Alembic commands ###
